projects:
  node:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: ${env:API_HOST}
  prisma:
    schemaPath: src/generated/graphql/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
