version: '3.7'

services:
  mysql:
    image: "mysql:${MYSQL_VERSION}"
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
  pma_admin:
    image: "phpmyadmin/phpmyadmin:${PMA_VERSION}"
    container_name: pma_admin
    depends_on:
      - mysql
    restart: always
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD
    ports:
      - '8080:80'

volumes:
  mysql: ~
