version: '3.7'

services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    container_name: prisma
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: ~
