version: '3.1'

## Install windows wsl and docker-ce
## connect windows docker daemon to wsl docker using tcp protocol

## Windows mysql terminal initial access command
# docker container exec -it mysql bash
# mysql -u root -p

services: 
  mysql-dev:
    container_name: di_dev_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7.24
    env_file: .docker.env
    ports:
      - '3306:3306'
