version: '3.7'

services:
  prisma:
    image: "prismagraphql/prisma:${PRISMA_VERSION}"
    container_name: prisma
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: "mysql:${MYSQL_VERSION}"
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: ~
